package com.amos.project4.socialMedia.facebook;

public enum Facebook_Data_Type {
	BIOGRAPHY,BIRTHDAY,LAST_POST,RELATIONSHIP,EDUCATION,WORKS,EVENTS,INTERESTS,FRIENDS,
	MUTUAL_FRIENDS,PROFILE_PICTURE,USERNAME
}
